name: Benchmark PR vs main

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
    paths:
      - '**.swift'
      - '**.yml'

permissions:  # By default, jobs can only read, even though running on pull_request_target event.
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-benchmark
  cancel-in-progress: true

env:
  OTEL_ENABLE_BENCHMARKS: true

jobs:
  test-comment-gen:
    outputs:
      comment_md: ${{ steps.encode-comment.outputs.comment_md }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate markdown file
        run: |
          echo '# Hello' >> comment.md
          echo '```swift' >> comment.md
          echo 'print(42)' >> comment.md
          echo '```' >> comment.md
      - name: Encodde markdown comment
        id: encode-comment
        run: |
          echo "comment_md=$(cat comment.md | base64 -w0)" | tee -a $GITHUB_OUTPUT

  test-comment:
    runs-on: ubuntu-latest
    needs: test-comment-gen
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Decode markdown comment
        run: |
          echo ${{ needs.test-comment-gen.outputs.comment_md }} | base64 -d | tee comment.md
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: comment.md
          comment-tag: benchmark
