name: Test Comment Gen

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'sb/test-comment-gen'

jobs:
  # Note that comment is done in a separate workflow
  test-comment-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate markdown file
        run: |
          echo '# Hello' >> comment.md
          echo '```swift' >> comment.md
          echo 'print(42)' >> comment.md
          echo '```' >> comment.md
      - uses: actions/upload-artifact@v4
        with:
          name: comment.md
          path: comment.md
